version: "3"
services:
  nginx:
    build:
      context: ./.docker/nginx
      dockerfile: Dockerfile
    ports:
      - "8080:80"
    networks:
      - internal
    volumes:
      - ./.docker/nginx/conf.d/:/etc/nginx/conf.d
  php:
    build:
      context: ./.docker/php
      dockerfile: Dockerfile
      args:
        USER_ID: ${UID:-0}
        GROUP_ID: ${GID:-0}
    tty: true
    environment:
      TERM: xterm-256color
      XDEBUG_MODE: develop,debug,coverage
      XDEBUG_CONFIG: client_host=host.docker.internal client_port=9003 discover_client_host=false start_with_request=trigger
    networks:
      - internal
    volumes:
      - .:/var/www/html
    user: ${UID}:${GID}
    working_dir: /var/www/html
  composer:
    image: composer
    volumes:
      - .:/app
    user: ${UID}:${GID}
    depends_on:
      - php
    command: composer install

networks:
  internal:
    driver: bridge
